packages:
  - .
  - testing
  - .xp/dev/*

ignore-workspace-root-check: true
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - edgedriver
  - geckodriver
